import { NextRequest, NextResponse } from "next/server";
import { createServiceClient } from "@/lib/supabase/server";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { homework_id, text_content } = body;

    if (!homework_id || !text_content) {
      return NextResponse.json(
        { error: "Missing homework_id or text_content" },
        { status: 400 }
      );
    }

    const supabase = await createServiceClient();

    // Get the current user
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Find the submission
    const { data: submission } = await supabase
      .from("submissions")
      .select("*")
      .eq("homework_id", homework_id)
      .eq("student_id", user.id)
      .eq("submission_type", "text")
      .single();

    if (!submission) {
      return NextResponse.json(
        { error: "Submission not found" },
        { status: 404 }
      );
    }

    if (!process.env.ANTHROPIC_API_KEY) {
      // No API key configured — skip AI check silently
      return NextResponse.json({
        status: "skipped",
        message: "AI check not configured (no API key)",
      });
    }

    // Call Anthropic API
    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": process.env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-haiku-4-5",
        max_tokens: 150,
        messages: [
          {
            role: "user",
            content: `You are an AI text analyzer for a school. Assess the following student homework submission for likelihood that it was generated by AI. Return ONLY a JSON object with exactly this format: {"label": "low"|"medium"|"high", "notes": "1-2 sentence reasoning"}. Do not include any other text, markdown, or explanation.\n\nStudent submission:\n${text_content}`,
          },
        ],
      }),
    });

    let label = "low";
    let notes = "Unable to analyze.";

    if (response.ok) {
      const data = await response.json();
      const assistantMessage = data.content?.[0]?.text || "";

      try {
        // Try to parse the JSON from the response
        const parsed = JSON.parse(assistantMessage.trim());
        if (
          parsed.label &&
          ["low", "medium", "high"].includes(parsed.label)
        ) {
          label = parsed.label;
          notes = parsed.notes || "No reasoning provided.";
        }
      } catch {
        // If parsing fails, try to extract label from text
        const lower = assistantMessage.toLowerCase();
        if (lower.includes("high")) label = "high";
        else if (lower.includes("medium")) label = "medium";
        else label = "low";
        notes = assistantMessage.slice(0, 200);
      }
    } else {
      notes = "AI check API call failed.";
    }

    // Update the submission with AI check results
    await supabase
      .from("submissions")
      .update({
        ai_check_label: label,
        ai_check_notes: notes,
      })
      .eq("id", submission.id);

    return NextResponse.json({ status: "ok", label, notes });
  } catch (error) {
    console.error("AI check error:", error);
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    );
  }
}