import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { createServerClient } from "@supabase/ssr";

const adminClient = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { autoRefreshToken: false, persistSession: false } }
);

const DEEPSEEK_API_KEY = process.env.DEEPSEEK_API_KEY || "";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { homework_id, text_content } = body;

    if (!homework_id || !text_content) {
      return NextResponse.json(
        { error: "Missing homework_id or text_content" },
        { status: 400 }
      );
    }

    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
      { cookies: { getAll() { return request.cookies.getAll(); }, setAll() {} } }
    );

    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const { data: submission } = await adminClient
      .from("submissions")
      .select("*")
      .eq("homework_id", homework_id)
      .eq("student_id", user.id)
      .eq("submission_type", "text")
      .single();

    if (!submission) {
      return NextResponse.json({ error: "Submission not found" }, { status: 404 });
    }

    if (!DEEPSEEK_API_KEY) {
      return NextResponse.json({ error: "AI service not configured" }, { status: 500 });
    }

    // Call DeepSeek to analyze the text for AI-generation likelihood
    const prompt = `You are an AI-detection expert. Analyze the following student homework submission and determine the likelihood (0-100%) that it was generated by an AI rather than written by a human student.

Look for these indicators:
- Overly perfect grammar and structure (AI hallmark)
- Repetitive sentence patterns or generic phrasing
- Formal transitional phrases used excessively (furthermore, moreover, in conclusion)
- Lack of personal voice, anecdotes, or opinions
- Very consistent paragraph lengths
- Self-referential AI language (e.g., "as an AI")
- Overly detailed but superficial coverage of the topic
- Unusual formality for a student assignment

Respond ONLY with a JSON object with these fields:
- percent (number 0-100): precise AI-likelihood percentage — use the FULL range (11, 23, 45, 67, 32, 78, etc.)
- label (string): "low" (0-33%), "medium" (34-66%), or "high" (67-100%)
- notes (string): 1-3 sentences explaining the analysis

STUDENT SUBMISSION:
${text_content}`;

    const deepseekRes = await fetch("https://api.deepseek.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${DEEPSEEK_API_KEY}`,
      },
      body: JSON.stringify({
        model: "deepseek-chat",
        max_tokens: 500,
        temperature: 0.2,
        messages: [
          {
            role: "system",
            content: "You are an AI-detection expert. You analyze student homework to detect AI-generated content. You ONLY respond with valid JSON objects, never markdown.",
          },
          {
            role: "user",
            content: prompt,
          },
        ],
      }),
    });

    if (!deepseekRes.ok) {
      const errText = await deepseekRes.text();
      console.error("DeepSeek AI-check error:", errText);
      return NextResponse.json({ error: "AI check service unavailable" }, { status: 502 });
    }

    const aiData = await deepseekRes.json();
    const responseText = aiData.choices?.[0]?.message?.content || "{}";

    // Parse JSON response
    let jsonStr = responseText.trim();
    jsonStr = jsonStr.replace(/^```json?\s*/i, "").replace(/\s*```$/i, "");
    const jsonMatch = jsonStr.match(/\{[\s\S]*\}/);
    jsonStr = jsonMatch ? jsonMatch[0] : jsonStr;

    let result: { percent: number; label: string; notes: string };
    try {
      result = JSON.parse(jsonStr);
    } catch {
      // Fallback to heuristic if AI fails
      const heuristicResult = heuristicAnalyze(text_content);
      result = {
        percent: heuristicResult.percent,
        label: heuristicResult.label,
        notes: heuristicResult.notes + " (local analysis — AI service unavailable)",
      };
    }

    // Clamp values
    const percent = Math.max(0, Math.min(Math.round(result.percent ?? 0), 100));
    let label: string;
    if (result.label === "low" || result.label === "medium" || result.label === "high") {
      label = result.label;
    } else {
      label = percent <= 33 ? "low" : percent <= 66 ? "medium" : "high";
    }
    const notes = result.notes || "Analysis completed.";

    // Save to database
    await adminClient
      .from("submissions")
      .update({ ai_check_label: label, ai_check_notes: notes })
      .eq("id", submission.id);

    return NextResponse.json({ status: "ok", percent, label, notes });
  } catch (error) {
    console.error("AI check error:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

/** Local fallback heuristic when DeepSeek is unavailable */
function heuristicAnalyze(text: string): { percent: number; label: string; notes: string } {
  const normalized = text.trim();
  const wordCount = normalized.split(/\s+/).length;
  const sentences = normalized.split(/[.!?]+/).filter((s) => s.trim().length > 0);
  const avgWordsPerSentence = sentences.length > 0 ? wordCount / sentences.length : 0;

  let score = 0;
  const reasons: string[] = [];

  if (wordCount < 20) {
    return { percent: 5, label: "low", notes: "Text too short to analyze meaningfully." };
  }

  if (avgWordsPerSentence > 25) {
    score += 25;
    reasons.push("long complex sentences");
  }

  const formalPhrases = [
    "in conclusion", "furthermore", "moreover", "nevertheless",
    "consequently", "it is important to note", "one could argue",
    "in other words", "as a result", "it should be noted",
  ];
  let formalCount = 0;
  const lowerText = normalized.toLowerCase();
  formalPhrases.forEach((phrase) => {
    formalCount += (lowerText.match(new RegExp(phrase, "g")) || []).length;
  });
  if (formalCount >= 3) {
    score += 30;
    reasons.push("heavy formal phrasing");
  } else if (formalCount >= 1) {
    score += 12;
  }

  const firstWords = sentences.map((s) => s.trim().split(/\s+/).slice(0, 2).join(" ").toLowerCase());
  const uniqueStarters = new Set(firstWords).size;
  if (uniqueStarters / Math.max(sentences.length, 1) < 0.5 && sentences.length > 3) {
    score += 17;
    reasons.push("repetitive sentence structure");
  }

  const paragraphs = normalized.split(/\n\n+/).filter((p) => p.trim().length > 0);
  if (paragraphs.length >= 3) {
    const paraLengths = paragraphs.map((p) => p.split(/\s+/).length);
    const avgPara = paraLengths.reduce((a, b) => a + b, 0) / paraLengths.length;
    const maxDev = Math.max(...paraLengths.map((l) => Math.abs(l - avgPara)));
    if (maxDev < avgPara * 0.3) {
      score += 12;
      reasons.push("uniform paragraph lengths");
    }
  }

  if (lowerText.includes("as an ai") || lowerText.includes("as a language model") || lowerText.includes("i am an ai")) {
    score += 50;
    reasons.push("self-referential AI phrasing");
  }

  const percent = Math.min(score, 100);
  const label = percent >= 67 ? "high" : percent >= 34 ? "medium" : "low";
  const notes = reasons.length > 0 ? "Detected: " + reasons.join("; ") + "." : "No strong AI patterns detected.";

  return { percent, label, notes };
}